// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a proposal is in its lifecycle.
 *
 * The transitions form a forward-only state machine:
 * `Draft → Deliberation → Voting → Closed`.
 * Backwards transitions are not permitted.
 */
export type ProposalStatus = "draft" | "deliberation" | "voting" | "closed";
