// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the author of a deliberation comment stands on the proposal.
 *
 * Required at comment creation. The structural label keeps deliberation
 * threads legible: "12 in support, 4 opposed, 7 neutral, 3 questions" is
 * derivable cheaply at the top of every thread.
 *
 * Independent of the author's actual vote — a `Support` comment can
 * precede a `No` vote, and that is allowed.
 */
export type Stance = "support" | "oppose" | "neutral" | "question";
