// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a voter chose on a proposal.
 *
 * `Abstain` is recorded explicitly. It is not the same as not voting —
 * abstain is a deliberate participation that registers presence and
 * neutrality. Tallies report yes / no / abstain separately.
 */
export type VoteChoice = "yes" | "no" | "abstain";
