// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for a single vote-cast event (append-only log row).
 */
export type VoteId = string;
