// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-negative vote weight.
 *
 * `Default` is `1.0` — the standard one-person-one-vote weight. Larger
 * weights arise from delegation accumulation; in v1 there is no other
 * reason for a non-unit base weight.
 */
export type Weight = string;
